### ISSUE TITLE
Add preloaders for log in and register

### ISSUE THREAD

**Issue by mohityadav0903** [mohityadav0903/Algoders-Community#11]

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, I would like to work on this issue for GSoC'22.

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, I have added the mentioned task i.e. Preloader for Login and Signup page. Here is an example -

![image](https://user-images.githubusercontent.com/59647563/156218380-0864712e-13ee-4410-aa20-a347eeae4223.png)

**Comment by Shubham29012001** [comment]
Hello @mohityadav0903, I noticed that in DropDownItems.jsx, the import has been changed to something else. The original package was "react-loader-spinner". That's creating the issue.

**Comment by mohityadav0903** [comment]
hey it's solved now i am reviewing your PR

**Comment by mohityadav0903** [comment]
hey @Shubham29012001 i have merged your PR. I  am closing this issue u can work on other issues if u want thanks
