### ISSUE TITLE
Blog Post Webpage

### ISSUE THREAD

**Issue by bhutani2002** [mohityadav0903/Algoders-Community#16]
**Describe the bug**
There's no form or something like inputs, through which the user can write their own tech blog with title, description to submit for the website . The blogs are directly fetched from the firebase database, as of now and the users can just view the blogs.

**To Reproduce**
1. Go to [Blogs](https://www.algoderscommunity.tech/blogs)
2. See error

**Expected behavior**
To create a form or inputs through which users can provide their tech blogs on the page. And the blogs will directly move to the firebase database. From there the blog will be fetched and shown on the 'Blogs' page. 

Posting functionality for a user will only open up on their login and not without login .

Are You working on the issue?
Yes

**Comment by bhutani2002** [comment]
@mohityadav0903 please review it once and provide your feedback .
Thank You

**Comment by mohityadav0903** [comment]
![image](https://user-images.githubusercontent.com/83297933/156591868-3ad10d9d-1c76-4998-a482-dc9a15d4e7ae.png)

**Comment by bhutani2002** [comment]
> ![image](https://user-images.githubusercontent.com/83297933/156591868-3ad10d9d-1c76-4998-a482-dc9a15d4e7ae.png)

It's I guess not visible on the website. Could you please provide the link for this page, because I didn't find it there.

**Comment by mohityadav0903** [comment]
hey For this u have to apply for writing role and for that we are having a form so that anyone can apply

**Comment by mohityadav0903** [comment]
ya plz

**Comment by bhutani2002** [comment]
> ya plz

Ok
