### ISSUE TITLE
Blog 'ALL' category

### ISSUE THREAD

**Issue by bhutani2002** [mohityadav0903/Algoders-Community#17]
**Describe the bug**
There's no 'ALL' tag(or category) on the blogs page header, through which the user can see all different types of blogs together. It's just on the initial page reload where all blogs are seen together, but after choosing any category, we cannot go back to ALL blogs category. 

**To Reproduce**
1. Go to [Blogs](https://www.algoderscommunity.tech/blogs)
2. See error

**Expected behavior**
'ALL' category should be included.

**Video**
We cannot again, see the 'jwt test 1' blog, as it is not under any category.

https://user-images.githubusercontent.com/84590758/156589696-6b39f339-7ea9-4663-ab16-d54481ddc826.mp4

Are you working on the issue?
Yes

**Comment by bhutani2002** [comment]
Hey @mohityadav0903 could you please review this issue and provide me a feedback on it . I guess I might need the firebase access, as all the category names come from firebase database as I went through the code and would require to add the category there.
Thank You

**Comment by mohityadav0903** [comment]
hey @bhutani2002 it's not firebase in the backend. I used mongodb for that. 
Btw i got your point u do not need to have backend access for that u can add a back arrow or back button for it

**Comment by bhutani2002** [comment]
> hey @bhutani2002 it's not firebase in the backend. I used mongodb for that. Btw i got your point u do not need to have backend access for that u can add a back arrow or back button for it

So, I guess now I can add a back arrow button now below every category.

**Comment by mohityadav0903** [comment]
ya u can work on it
