### ISSUE TITLE
Page to "Apply as a Mentor" 

### ISSUE THREAD

**Issue by anishacse2018** [mohityadav0903/Algoders-Community#18]
In the website, there is a button "Apply Here" as a Mentor, but when I click on it, its staying in the same page instead of getting redirected to a new page. I would like to work on that page.

**Comment by mohityadav0903** [comment]
hey @anishacse2018 nice to see your attention for the issues. We need a new form for that. Go ahead and create a page for it that contains a form ith name email skills and a drive link section to upload CV

**Comment by anishacse2018** [comment]
Yeah, I will start working on it. Thanks.

**Comment by anishacse2018** [comment]
I have completed this task. Could you review the code and tell me the next steps.
