### ISSUE TITLE
Re-designing Login & Register Form

### ISSUE THREAD

**Issue by thefstalphabet** [mohityadav0903/Algoders-Community#22]
Login & Register forms need to be re-design, and there are buttons in both pages to be removed that are unnecessary.

Can you please assign this to me? under GSSOC'22.

![s2022-03-05 123035](https://user-images.githubusercontent.com/69709410/156872641-39d293ff-9f4c-469a-bb01-8cccd206e6a3.jpg)

![Screenshot 2022-03-05 123129](https://user-images.githubusercontent.com/69709410/156872642-65b60e7f-0a1e-45ee-bd32-6db350851c40.jpg)

**Comment by mohityadav0903** [comment]
hey @thefstalphabet go ahead

**Comment by thefstalphabet** [comment]
Great then, I'll start working on it.
