### ISSUE TITLE
Bug: Could Not Fetch User Details in Navbar Due to Wrong JSON Configuration

### ISSUE THREAD

**Issue by Shubham29012001** [mohityadav0903/Algoders-Community#23]
When we login into the application, the Navbar must print Hello "Username" but instead, it's printing only Hello. Similarly to profile pic and role. It's happening due to the wrong JSON configuration. The current one is user.username, user.role, user.profilePic but instead the working one should be user.others.username, user.others.role, and user. others.profilePic.

1. Go to Login Page
2. log in to the System
3. In the Navbar, you will see only Hello but no username, etc are printed due to the wrong JSON configuration.

The expected behavior is to see the correct user role, profilePic, and username.

Current -

![image](https://user-images.githubusercontent.com/59647563/156872602-cb84abe5-fb90-49ea-bc48-f544f6035e73.png)

Expected -

![image](https://user-images.githubusercontent.com/59647563/156872569-d0ac2678-5440-4e5d-8199-566dd64366f2.png)

Hey @mohityadav0903, please assign it to me. II would like to work on it for GSSoC '22.

**Comment by Dcode-k** [comment]
hey @Shubham29012001 you can start working on it.

**Comment by Shubham29012001** [comment]
Hey @Dcode-k, I have raised a pull request to fix this bug issue.
