### ISSUE TITLE
make contact page

### ISSUE THREAD

**Issue by mohityadav0903** [mohityadav0903/Algoders-Community#3]

**Comment by varisha-025** [comment]
Hello @mohityadav0903. I am a participant in GSSoC 2022 and I would like to work on this issue. Please assign this issue to me.

**Comment by Akku2016** [comment]
hi, Can you please assign me to this problem. Being a GSSOC'22 participant I can start working on it from March 1st.plz little bit explain it

**Comment by varisha-025** [comment]
Hello @mohityadav0903. I am a participant in GSSoC 2022 and I would like to work on this issue. Can you assign this to me?

**Comment by mohityadav0903** [comment]
hey @Akku2016 you need to add a contact section before the footer.

**Comment by mohityadav0903** [comment]
hey @Akku2016 commit the code to your branch and then push it

**Comment by Daksh-jha** [comment]
Hey @mohityadav0903 , Can I work next on the issue if it is yet not done ?

**Comment by Akku2016** [comment]
already I done @Daksh-jha I will make a PR for this isssue
