### ISSUE TITLE
Update Contact Us Section

### ISSUE THREAD

**Issue by shivam123-dev** [mohityadav0903/Algoders-Community#35]
## Current Contact Us Section
![image](https://user-images.githubusercontent.com/81038095/157407420-91d33ad7-e217-4bbb-a7f9-8d660d6ee06a.png)

## Updated Contact Us Section
![image](https://user-images.githubusercontent.com/81038095/157407313-27c10542-5b3c-4b04-9728-b6473fe380ea.png)

@mohityadav0903 Please assign me this issue under GSSOC'22

**Comment by mohityadav0903** [comment]
hey @shivam123-dev u can work on it

**Comment by shivam123-dev** [comment]
@mohityadav0903 Please review PR #37
