### ISSUE TITLE
Need proper alignment

### ISSUE THREAD

**Issue by thefstalphabet** [mohityadav0903/Algoders-Community#36]
Need to align paragraphs information present on the home page.
i.e. If para is present on the left, it needs alignment to be left, and same to right.

![Screenshot 2022-03-10 083441](https://user-images.githubusercontent.com/69709410/157580856-9683f4f0-b0a8-47b9-8db9-d114d815af5b.jpg)

![Screenshot 2022-03-10 083425](https://user-images.githubusercontent.com/69709410/157580863-8e30569f-bd7b-4fb8-8e68-7115c9666a0f.jpg)

![Screenshot 2022-03-10 083504](https://user-images.githubusercontent.com/69709410/157580868-0c534ad8-23ea-40c2-8408-3cd4aae846c5.jpg)

Can you please assign this to me? under GSSOC'22.

**Comment by gursimran0410** [comment]
@thefstalphabet Assign this to me under GSSOC'22.

**Comment by mohityadav0903** [comment]
hey @thefstalphabet u can work on this

**Comment by BIKRAM-SAHA** [comment]
Hi @mohityadav0903 it has been long since the issue was raised. Would love to volunteer to work on this issue if it is available for assignment

**Comment by BIKRAM-SAHA** [comment]
@mohityadav0903 is this issue available for grab? Would love to volunteer for this.
