### ISSUE TITLE
Add scrolling effects 

### ISSUE THREAD

**Issue by mohityadav0903** [mohityadav0903/Algoders-Community#4]
add fade in fade out effects when we scroll to down or upward

**Comment by nitishsaini706** [comment]
hi @mohityadav0903 . I would like to work on this , im GSSOC 2022 contributor

**Comment by mohityadav0903** [comment]
hey @nitishsaini706 you can work on this issue. Need some cool fade in fade out etc. effects on scrolling

**Comment by nitishsaini706** [comment]
@mohityadav0903 On it

**Comment by nitishsaini706** [comment]
hey @mohityadav0903 just created a pr ,
i've applied scrolling effect on about us page component only

**Comment by anishacse2018** [comment]
Hey, I would like to work on this issue.
