### ISSUE TITLE
Fix Blogs page cards alignment and animation

### ISSUE THREAD

**Issue by Anirban-1490** [mohityadav0903/Algoders-Community#49]
**Describe the bug**
blogs page cards hover style seems wrong and it's alignment too

**Screenshots**

![Opera Snapshot_2022-04-03_160338_algo-testsite herokuapp com](https://user-images.githubusercontent.com/82874704/161423479-d054c17c-0c6d-4f1e-b293-310a5925167e.png)

**Comment by Anirban-1490** [comment]
assign me this under GSSOC22

**Comment by mohityadav0903** [comment]
hey @Anirban-1490 i have already created a bug for this 
plz comment on #21
