### ISSUE TITLE
Footer Improvements

### ISSUE THREAD

**Issue by aaryahjolia** [mohityadav0903/Algoders-Community#51]
**Describe the bug**
In footer, instagram logo needs to be updated and the image should link to the main website.

**Expected behavior**
A more better footer.

**Screenshots**
![GSSoC](https://user-images.githubusercontent.com/82600388/161591060-cddc6827-f5b0-49ca-8500-04ab1f13f76b.png)

**Additional context**
I'm a GSSoC contributor.

**Comment by mohityadav0903** [comment]
hey @aaryahjolia go ahead
