### ISSUE TITLE
Cards overlapping

### ISSUE THREAD

**Issue by Adhetya** [mohityadav0903/Algoders-Community#52]
**Describe the bug**
The cards are overlapping not making the UI look good

**Expected behavior**
Cards should be given adequate spacing and be clear to read

**Screenshots**

<img width="1440" alt="Screenshot 2022-04-05 at 6 38 39 PM" src="https://user-images.githubusercontent.com/20537150/161761154-cbee8e29-efcd-4cd3-9cae-c392560146c6.png">

**Additional context**
Also, text is not very clear in the background. Icon colour could be changed along with heading colour

**Comment by mohityadav0903** [comment]
hey @Adhetya go ahead
