### ISSUE TITLE
Site Loads too Slow due to AoS and Image Size Not Proper on Homepage

### ISSUE THREAD

**Issue by Shubham29012001** [mohityadav0903/Algoders-Community#55]
**Describe the bug**
When we visit the homepage, the site loads too slowly due to the high aos configuration. Also, the images on the homepages are not properly specified leading to a bad user experience.

**To Reproduce**
1. Go to 'Homepage'
2. Scroll down and you will see how slow the animate loads
3. Scrolling down further you will see every small image

**Expected behavior**
A lower AoS second configuration and proper dimension for images should be specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/59647563/162785454-4e8db331-ddc3-42c2-a693-9d246338e255.png)

I would like to work on this issue for GSSoC'22? I have discussed this with you on the discord server regarding the issue.

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, can you please check out the issue? I have discussed this with you on the Discord server.

**Comment by mohityadav0903** [comment]
hey @Shubham29012001 u can work on it

**Comment by mohityadav0903** [comment]
hey @Shubham29012001 the separate about page is looking bad due to your changes
![image](https://user-images.githubusercontent.com/83297933/162818911-79fafcad-ab50-4dc3-86a3-570dc3ed0e9e.png)

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, can you please assign GSSoC label with appropriate level for the issue?

**Comment by mohityadav0903** [comment]
i have already added labels to the pr

**Comment by Shubham29012001** [comment]
Yup, my bad I didn't noticed the PR merged. Sorry for that. Apart from it is there any feature or issue you want to be done on the site, it would help us (contributors) to learn and implement something new everytime.

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, I am sorry for that I didn't checked the about us page. It's happening due to a single line code in card.css. I will fix it and re-open the pull request. Sorry for the issue I didn't want to broke the site.

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, I have opened up the PR for it. Please have a look at it and lastly, I am really sorry for the poor PR which got merged due to me.
