### ISSUE TITLE
Making heading of the navbar more stylish 

### ISSUE THREAD

**Issue by nitishsaini706** [mohityadav0903/Algoders-Community#60]
![issue](https://user-images.githubusercontent.com/39373956/162941617-c8998bf2-fca1-49b2-a3cd-06f723b56851.png)

Making algoders community label in navbar more stylish on hover ,
Instagram icon is not aligned ,
also fixing issue #6

**Comment by mohityadav0903** [comment]
hey @nitishsaini706 plz update the project by forking again and then create issues.
it's already solved
