### ISSUE TITLE
Adding Animations in home page

### ISSUE THREAD

**Issue by aaryahjolia** [mohityadav0903/Algoders-Community#65]
**Describe the bug**
Adding animations at several places will look good for users.

**To Reproduce**
1. Go to website
2. Scroll down to whole website
3. See no animations

**Expected behavior**
Animations at lots of places in home page

**Screenshots**

Animation on hover : 
![image](https://user-images.githubusercontent.com/82600388/166564110-e22b5120-fb48-4a6e-a419-f4ee45e55384.png)

Taking button in new line : 
![image](https://user-images.githubusercontent.com/82600388/166564245-ee888945-80bd-42b8-bd81-82377f7ff8b5.png)

Contact us page improvements : 
![image](https://user-images.githubusercontent.com/82600388/166564817-8538c66c-9e49-4e51-aab2-1c5acc3be838.png)

**Comment by mohityadav0903** [comment]
hey @aaryahjolia u can work on it

**Comment by mohityadav0903** [comment]
hey @aaryahjolia any updates?

**Comment by aaryahjolia** [comment]
As my semester end exams are going on, I will make a PR before 21st.
