### ISSUE TITLE
Sequence of menu

### ISSUE THREAD

**Issue by nishtha53** [mohityadav0903/Algoders-Community#80]
**Describe the bug**
Sequence of menu should be change not looking good right now.

**To Reproduce**
1. Go to home page
2. Can we change sequence of menu => left side logo should come, in center home,about,contact, blogs should and in right login signup should come

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/68805896/194038653-12d22d69-8a49-4e7b-8664-e47d42b29ead.png)

**Comment by nishtha53** [comment]
@mohityadav0903 Please assign this to me

**Comment by mohityadav0903** [comment]
hey @nishtha53 the issue is already mentioned in #74 
u can comment there

**Comment by nishtha53** [comment]
okay sure
